Update build framework (#58)
* Remove config.h.in file from version control
* Remove autogen script
* Add with-hypre-dir option
* Update install instructions
* Check for srun or mpirun
* Improve checking for dependency libraries

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -26,18 +26,20 @@ docs: doxygen-doc
 	@echo "Built user's manual documentation (Sphinx)"
 
 check:
-	@command -v mpirun >/dev/null 2>&1 || { echo >&2 "mpirun not found!"; exit 1; }
-	@mpirun -np 1 ./hypredrive examples/ex1.yml > /dev/null 2>&1
+	@{ command -v mpirun >/dev/null 2>&1 && MPIRUN=mpirun && NPFLAG=-np; } || \
+	{ command -v srun >/dev/null 2>&1 && MPIRUN=srun && NPFLAG=-n; } || \
+	{ echo >&2 "Neither mpirun nor srun found!"; exit 1; }
+	@$(MPIRUN) $(NPFLAG) 1 ./hypredrive examples/ex1.yml > /dev/null 2>&1
 	@if test $$? -eq 0 ; then \
-		echo "Running with 1 MPI process... passed!"; \
+		echo "Running ex1 with 1 MPI process... passed!"; \
 	else \
-		echo "Running with 1 MPI process... failed!"; \
+		echo "Running ex1 with 1 MPI process... failed!"; \
 		exit 1; \
 	fi
-	@mpirun -np 4 ./hypredrive examples/ex2.yml > /dev/null 2>&1
+	@$(MPIRUN) $(NPFLAG) 4 ./hypredrive examples/ex2.yml > /dev/null 2>&1
 	@if test $$? -eq 0 ; then \
-		echo "Running with 4 MPI process... passed!"; \
+		echo "Running ex2 with 4 MPI processes... passed!"; \
 	else \
-		echo "Running with 4 MPI process... failed!"; \
+		echo "Running ex2 with 4 MPI processes... failed!"; \
 		exit 1; \
 	fi
